#!/bin/bash
# ============================================================
# modules/18-monitors.sh — Detect native monitor resolution
#                           and write monitors.conf
# ============================================================
# Runs AFTER dotfiles are copied (module 02) so monitors.conf
# already exists and can be safely overwritten.
# ============================================================
should_skip "monitors" && return 0

_monitors_conf="$HOME/.config/hypr/monitors.conf"
_profiles_dir="$HOME/.config/hypr/Monitor_Profiles"

log_action "Detecting monitor resolution..."

# ── Helper: detect via hyprctl (available if Hyprland is running) ──
_detect_hyprctl() {
  if ! command -v hyprctl &>/dev/null; then return 1; fi
  if ! hyprctl monitors &>/dev/null 2>&1; then return 1; fi

  # Parse each connected monitor: "name WxH@Hz at Ox0 scale S"
  hyprctl -j monitors 2>/dev/null | \
    python3 -c "
import json, sys
data = json.load(sys.stdin)
for m in data:
    name  = m.get('name', '')
    w     = m.get('width', 0)
    h     = m.get('height', 0)
    rr    = m.get('refreshRate', 60)
    ox    = m.get('x', 0)
    oy    = m.get('y', 0)
    scale = m.get('scale', 1.0)
    print(f'{name} {w} {h} {rr:.0f} {ox} {oy} {scale}')
" 2>/dev/null
}

# ── Helper: detect via wlr-randr (Wayland, no compositor needed) ──
_detect_wlr_randr() {
  if ! command -v wlr-randr &>/dev/null; then return 1; fi
  # Output format: "HDMI-A-1 "1920x1080" @ 60.00 Hz (preferred, current)"
  wlr-randr 2>/dev/null | awk '
    /^[A-Za-z]/ { name = $1 }
    /current/   {
      match($0, /([0-9]+)x([0-9]+)/, res)
      match($0, /@ ([0-9.]+)/, rr)
      if (res[1] && rr[1]) printf "%s %s %s %d 0 0 1.0\n", name, res[1], res[2], int(rr[1]+0.5)
    }
  '
}

# ── Helper: detect via xrandr (XWayland fallback) ──
_detect_xrandr() {
  if ! command -v xrandr &>/dev/null; then return 1; fi
  # Output: "HDMI-1 connected 1920x1080+0+0 (normal ..."
  xrandr 2>/dev/null | awk '
    /connected/ && !/disconnected/ {
      name = $1
      match($0, /([0-9]+)x([0-9]+)\+([0-9]+)\+([0-9]+)/, m)
      if (m[1]) printf "%s %s %s 60 %s %s 1.0\n", name, m[1], m[2], m[3], m[4]
    }
  '
}

# ── Gather monitor data using the best available tool ──
_monitor_data=""

if _monitor_data="$(_detect_hyprctl)" && [[ -n "$_monitor_data" ]]; then
  log_info "Monitor data sourced from hyprctl."
elif _monitor_data="$(_detect_wlr_randr)" && [[ -n "$_monitor_data" ]]; then
  log_info "Monitor data sourced from wlr-randr."
elif _monitor_data="$(_detect_xrandr)" && [[ -n "$_monitor_data" ]]; then
  log_info "Monitor data sourced from xrandr."
else
  log_warn "Could not detect monitor resolution (no hyprctl/wlr-randr/xrandr available)."
  log_warn "Falling back to 1920x1080@60."
  # Use sentinel token "FALLBACK" so the parse loop can handle it
  _monitor_data="FALLBACK 1920 1080 60 0 0 1.0"
fi

# ── Build monitors.conf from detected data ──
# Each line of _monitor_data:  NAME WIDTH HEIGHT REFRESHRATE OFFSET_X OFFSET_Y SCALE
# NAME == "FALLBACK" means use wildcard (,) instead of a specific output name.
# Hyprland format: monitor=NAME,WxH@RR,OXxOY,SCALE

_conf_lines=""
_monitor_count=0

while IFS=' ' read -r _name _w _h _rr _ox _oy _scale; do
  [[ -z "$_name" || -z "$_w" || -z "$_h" ]] && continue

  # Round refresh rate to nearest integer
  _rr_int=$(printf '%.0f' "$_rr" 2>/dev/null || echo "60")
  # Round scale to 1 decimal place
  _scale_fmt=$(printf '%.1f' "${_scale:-1.0}" 2>/dev/null || echo "1.0")

  # FALLBACK sentinel → wildcard monitor name
  if [[ "$_name" == "FALLBACK" ]]; then
    _line="monitor=,${_w}x${_h}@${_rr_int},auto,${_scale_fmt}"
    log_info "  Fallback: wildcard → ${_w}x${_h}@${_rr_int}Hz scale ${_scale_fmt}"
  else
    _line="monitor=${_name},${_w}x${_h}@${_rr_int},${_ox}x${_oy},${_scale_fmt}"
    log_info "  Detected: ${_name} → ${_w}x${_h}@${_rr_int}Hz offset ${_ox},${_oy} scale ${_scale_fmt}"
  fi

  _conf_lines+="${_line}"$'\n'
  _monitor_count=$((_monitor_count + 1))
done <<< "$_monitor_data"

if [[ -z "$_conf_lines" || $_monitor_count -eq 0 ]]; then
  log_warn "Monitor data was empty after parsing. Falling back to 1920x1080@60."
  _conf_lines="monitor=,1920x1080@60,auto,1.0"$'\n'
  _monitor_count=1
fi

# ── Write monitors.conf ──
mkdir -p "$(dirname "$_monitors_conf")"

cat > "$_monitors_conf" <<EOF
# HyprFlux — Auto-generated monitor config
# Generated by modules/18-monitors.sh at install time.
# To reconfigure: use SUPER+SHIFT+E → "Configure Monitors (nwg-displays)"
#                 or SUPER+SHIFT+E → "Choose Monitor Profiles"
#
# See Hyprland wiki: https://wiki.hyprland.org/Configuring/Monitors/
# Use \`hyprctl monitors\` to query live monitor info.

# Detected monitors (${_monitor_count} connected)
${_conf_lines}
# Fallback: any monitor not matched above uses preferred mode
monitor=,preferred,auto,1

# NOTE: for laptop lid behaviour, see UserConfigs/Laptops.conf
# QEMU/KVM virtual display example:
#monitor=Virtual-1,1920x1080@60,auto,1

# Mirror example:
#monitor=HDMI-A-1,preferred,auto,1,mirror,eDP-1

# 10-bit support (may break screen capture):
#monitor=,preferred,auto,1,bitdepth,10
EOF

log_ok "monitors.conf written with ${_monitor_count} detected monitor(s)."

# ── Also save as the default profile so it can be restored later ──
mkdir -p "$_profiles_dir"
cp "$_monitors_conf" "$_profiles_dir/default.conf"
log_ok "Saved as Monitor_Profiles/default.conf."

unset _monitors_conf _profiles_dir _monitor_data _conf_lines _monitor_count
unset _name _w _h _rr _rr_int _ox _oy _scale _scale_fmt _line
