#!/bin/bash
# HyprFlux — https://github.com/ahmad9059/HyprFlux
# ============================================================
# sync-colors.sh — regenerate ALL color files from ONE source:
#   .config/hypr/hyprflux-colors/hyprflux-colors.conf
#
# Generated (do NOT edit by hand):
#   hyprflux-colors.lua                 (hyprland Lua)
#   rofi/wallust/hyprflux-colors.rasi   (rofi)
#   waybar/hyprflux-colors.css          (waybar, swaync, wlogout)
#   kitty/kitty-colors.conf             (kitty, included from kitty.conf)
#   foot/colors.ini                     (foot, included from foot.ini)
#
# Usage: utilities/sync-colors.sh
# ============================================================

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$REPO_DIR/.config/hypr/hyprflux-colors/hyprflux-colors.conf"

# ---- parse the source palette ----
declare -A COLORS
while IFS= read -r line; do
  case "$line" in
    \$*=*)
      name="${line%% = *}"; name="${name#\$}"
      value="${line#*= }"
      value="${value%%#*}"            # strip trailing comments
      value="${value%"${value##*[![:space:]]}"}"  # right-trim
      case "$value" in
        rgb\(*\)|rgba\(*\)) COLORS["$name"]="$value" ;;
      esac
      ;;
  esac
done < "$SRC"

hex() { echo "$1" | sed -E 's/^rgba?\(([0-9A-Fa-f]+)\)$/\1/'; }
rgba_dec() { # rgba(RRGGBBAA) -> "r,g,b,a" decimals
  local h a
  h="$(hex "$1")"; a="${h:6:2}"
  printf '%d,%d,%d,%s' 0x"${h:0:2}" 0x"${h:2:2}" 0x"${h:4:2}" "$(python3 -c "print(round(int('$a',16)/255,3))")"
}

# ================= 1. hyprflux-colors.lua (hyprland) =================
LUA="$REPO_DIR/.config/hypr/hyprflux-colors.lua"
{
  echo "-- HyprFlux — https://github.com/ahmad9059/HyprFlux"
  echo "-- HyprFlux static color palette (GENERATED by utilities/sync-colors.sh)"
  echo "-- Single source: .config/hypr/hyprflux-colors/hyprflux-colors.conf"
  echo "-- Do not edit by hand."
  echo ""
  echo "local colors = {"
  for name in background foreground cursor color0 color1 color2 color3 color4 color5 color6 color7 color8 color9 color10 color11 color12 color13 color14 color15; do
    [ -n "${COLORS[$name]:-}" ] && printf '    %s = "rgba(%sff)",\n' "$name" "$(hex "${COLORS[$name]}" | cut -c1-6)"
  done
  echo "}"
  echo ""
  echo "return colors"
} > "$LUA"
echo "generated: hyprflux-colors.lua"

# ================= 2. rofi/wallust/hyprflux-colors.rasi =================
RASI="$REPO_DIR/.config/rofi/wallust/hyprflux-colors.rasi"
{
  echo "/* HyprFlux — https://github.com/ahmad9059/HyprFlux */"
  echo "/* HyprFlux static color palette (GENERATED by utilities/sync-colors.sh) */"
  echo "/* Static file — colors are not regenerated at runtime. */"
  echo ""
  echo "* {"
  echo "active-background: #$(hex "${COLORS[rofi_active]}");"
  echo "active-foreground: #$(hex "${COLORS[rofi_foreground]}");"
  echo "normal-background: #$(hex "${COLORS[rofi_background]}");"
  echo "normal-foreground: #$(hex "${COLORS[rofi_foreground]}");"
  echo "urgent-background: #$(hex "${COLORS[rofi_urgent]}");"
  echo "urgent-foreground: #$(hex "${COLORS[rofi_foreground]}");"
  echo ""
  echo "alternate-active-background: #$(hex "${COLORS[rofi_alt_active]}");"
  echo "alternate-active-foreground: #$(hex "${COLORS[rofi_foreground]}");"
  echo "alternate-normal-background: #$(hex "${COLORS[rofi_background]}");"
  echo "alternate-normal-foreground: #$(hex "${COLORS[rofi_foreground]}");"
  echo "alternate-urgent-background: #$(hex "${COLORS[rofi_background]}");"
  echo "alternate-urgent-foreground: #$(hex "${COLORS[rofi_foreground]}");"
  echo ""
  echo "selected-active-background: #$(hex "${COLORS[rofi_sel_active]}");"
  echo "selected-active-foreground: #$(hex "${COLORS[rofi_foreground]}");"
  echo "selected-normal-background: #$(hex "${COLORS[rofi_sel_normal]}");"
  echo "selected-normal-foreground: #$(hex "${COLORS[rofi_foreground]}");"
  echo "selected-urgent-background: #$(hex "${COLORS[rofi_sel_urgent]}");"
  echo "selected-urgent-foreground: #$(hex "${COLORS[rofi_foreground]}");"
  echo ""
  echo "background-color: #$(hex "${COLORS[rofi_background]}");"
  echo "background: rgba(0,0,0,0.7);"
  echo "background-alt: rgba($(rgba_dec "rgba($(hex "${COLORS[rofi_background]}")aa)"));"
  echo "foreground: #$(hex "${COLORS[rofi_foreground]}");"
  echo "border-color: #$(hex "${COLORS[rofi_border]}");"
  echo ""
  echo "/* master-config references */"
  echo "rofi-selected: #$(hex "${COLORS[rofi_selected]}");"
  echo "rofi-text-selected: #$(hex "${COLORS[rofi_text_sel]}");"
  echo "rofi-text: #$(hex "${COLORS[rofi_text]}");"
  echo "rofi-text-2: #$(hex "${COLORS[rofi_text_2]}");"
  echo "rofi-bg: #$(hex "${COLORS[rofi_bg_2]}");"
  echo ""
  for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do
    echo "color$i: #$(hex "${COLORS[rofi_color$i]}");"
  done
  echo "}"
} > "$RASI"
echo "generated: rofi/wallust/hyprflux-colors.rasi"

# ================= 3. waybar/hyprflux-colors.css (waybar/swaync/wlogout) =================
CSS="$REPO_DIR/.config/waybar/hyprflux-colors.css"
{
  echo "/* HyprFlux — https://github.com/ahmad9059/HyprFlux */"
  echo "/* HyprFlux static color palette (GENERATED by utilities/sync-colors.sh) */"
  echo ""
  echo "@define-color foreground #$(hex "${COLORS[foreground]}");"
  echo "@define-color background #$(hex "${COLORS[background]}");"
  echo "@define-color background-alt rgba($(rgba_dec "rgba($(hex "${COLORS[background]}")40)"));"
  echo "@define-color background-glass rgba($(rgba_dec "rgba($(hex "${COLORS[background]}")99)"));"
  echo "@define-color background-clear rgba(1,1,2,0);"
  echo "@define-color cursor #$(hex "${COLORS[cursor]}");"
  echo ""
  for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do
    echo "@define-color color$i #$(hex "${COLORS[color$i]}");"
  done
  echo ""
  echo "/* Navbar palette (catppuccin-mocha look) */"
  for n in base mantle crust text subtext0 subtext1 surface0 surface1 surface2 overlay0 overlay1 overlay2 blue lavender sapphire sky teal green yellow peach maroon red mauve pink flamingo rosewater; do
    echo "@define-color $n #$(hex "${COLORS[bar_$n]}");"
  done
  echo "@define-color bar-bg-alt #$(hex "${COLORS[bar_bg_alt]}");"
  echo "@define-color bar-main-bg #$(hex "${COLORS[bar_main_bg]}");"
  echo ""
  echo "/* Notifications (swaync) */"
  echo "@define-color noti-bg #$(hex "${COLORS[notif_bg]}");"
  echo "@define-color noti-bg-alt #$(hex "${COLORS[notif_bg]}");"
  echo "@define-color noti-bg-hover #$(hex "${COLORS[notif_bg]}");"
  echo "@define-color noti-border-color @color12;"
  echo "@define-color text-color #$(hex "${COLORS[notif_fg]}");"
  echo "@define-color noti-fg-dim rgba($(rgba_dec "${COLORS[notif_fg_dim]}"));"
  echo "@define-color noti-close-bg #$(hex "${COLORS[notif_close_bg]}");"
  echo "@define-color noti-accent #$(hex "${COLORS[notif_accent]}");"
  echo "@define-color noti-dnd-text #$(hex "${COLORS[notif_dnd_text]}");"
  echo "@define-color noti-progress #$(hex "${COLORS[notif_progress]}");"
  echo "@define-color noti-text-sel #$(hex "${COLORS[notif_text_sel]}");"
  echo ""
  echo "/* Logout (wlogout) */"
  echo "@define-color logout-bg rgba($(rgba_dec "${COLORS[logout_bg]}"));"
  echo "@define-color logout-btn-bg rgba($(rgba_dec "${COLORS[logout_btn_bg]}"));"
  echo "@define-color logout-hover-bg #$(hex "${COLORS[logout_hover_bg]}");"
  echo "@define-color logout-hover-text #$(hex "${COLORS[logout_hover_text]}");"
} > "$CSS"
echo "generated: waybar/hyprflux-colors.css"

# ================= 4. kitty/kitty-colors.conf =================
KITTY="$REPO_DIR/.config/kitty/kitty-colors.conf"
{
  echo "# HyprFlux — https://github.com/ahmad9059/HyprFlux"
  echo "# HyprFlux terminal color palette (GENERATED by utilities/sync-colors.sh)"
  echo "# Single source: hyprflux-colors.conf (\$term_* section)"
  echo "# Included from kitty.conf — do not edit by hand."
  echo ""
  echo "foreground         #$(hex "${COLORS[term_foreground]}")"
  echo "background         #$(hex "${COLORS[term_background]}")"
  echo "cursor             #$(hex "${COLORS[term_cursor]}")"
  echo ""
  for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do
    echo "color$i            #$(hex "${COLORS[term_color$i]}")"
  done
} > "$KITTY"
echo "generated: kitty/kitty-colors.conf"

# ================= 5. foot/colors.ini =================
FOOT="$REPO_DIR/.config/foot/colors.ini"
{
  echo "# HyprFlux — https://github.com/ahmad9059/HyprFlux"
  echo "# HyprFlux terminal color palette (GENERATED by utilities/sync-colors.sh)"
  echo "# Single source: hyprflux-colors.conf (\$term_* section)"
  echo "# Included from foot.ini — do not edit by hand."
  echo ""
  echo "[colors]"
  echo "background=#$(hex "${COLORS[term_background]}")"
  echo "foreground=#$(hex "${COLORS[term_foreground]}")"
  echo ""
  echo "## Normal/regular colors (color palette 0-7)"
  for i in 0 1 2 3 4 5 6 7; do
    echo "regular$i=#$(hex "${COLORS[term_color$i]}")"
  done
  echo ""
  echo "## Bright colors (color palette 8-15)"
  for i in 8 9 10 11 12 13 14 15; do
    echo "bright$i=#$(hex "${COLORS[term_color$i]}")"
  done
} > "$FOOT"
echo "generated: foot/colors.ini"

# ================= 8. swaync + wlogout inline color blocks =================
# GTK4's @define-color does not reliably propagate from @import'd files, so
# swaync/wlogout get a self-contained GENERATED color block instead.
inject_css_block() { # $1 = file, $2 = block
  local file="$1" block="$2" start="/* ==== GENERATED by sync-colors.sh — do not edit ==== */" end="/* ==== END GENERATED ==== */"
  python3 - "$file" "$start" "$end" "$block" <<'PYEOF'
import sys
f, start, end, block = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]
block = block.replace("\\n", "\n")
s = open(f).read()
# strip every existing generated block (idempotent), then prepend one fresh block
parts = s.split(start)
head = parts[0]
for p in parts[1:]:
    if end in p:
        p = p[p.index(end) + len(end):]
    head += p
s = start + "\n" + block + end + "\n" + head.lstrip("\n")
open(f, "w").write(s)
PYEOF
}

SWAYNC_BLOCK=""
SWAYNC_BLOCK+="@define-color color12 #$(hex "${COLORS[color12]}");\n"
SWAYNC_BLOCK+="@define-color foreground #$(hex "${COLORS[foreground]}");\n"
SWAYNC_BLOCK+="@define-color text-color #$(hex "${COLORS[notif_fg]}");\n"
SWAYNC_BLOCK+="@define-color noti-bg #$(hex "${COLORS[notif_bg]}");\n"
SWAYNC_BLOCK+="@define-color noti-bg-alt #$(hex "${COLORS[notif_bg]}");\n"
SWAYNC_BLOCK+="@define-color noti-bg-hover #$(hex "${COLORS[notif_bg]}");\n"
SWAYNC_BLOCK+="@define-color noti-border-color @color12;\n"
SWAYNC_BLOCK+="@define-color noti-fg-dim rgba($(rgba_dec "${COLORS[notif_fg_dim]}"));\n"
SWAYNC_BLOCK+="@define-color noti-close-bg #$(hex "${COLORS[notif_close_bg]}");\n"
SWAYNC_BLOCK+="@define-color noti-accent #$(hex "${COLORS[notif_accent]}");\n"
SWAYNC_BLOCK+="@define-color noti-dnd-text #$(hex "${COLORS[notif_dnd_text]}");\n"
SWAYNC_BLOCK+="@define-color noti-progress #$(hex "${COLORS[notif_progress]}");\n"
inject_css_block "$REPO_DIR/.config/swaync/style.css" "$SWAYNC_BLOCK"
echo "injected: swaync/style.css color block"

WLOGOUT_BLOCK=""
WLOGOUT_BLOCK+="@define-color text-color #$(hex "${COLORS[notif_fg]}");\n"
WLOGOUT_BLOCK+="@define-color logout-bg rgba($(rgba_dec "${COLORS[logout_bg]}"));\n"
WLOGOUT_BLOCK+="@define-color logout-btn-bg rgba($(rgba_dec "${COLORS[logout_btn_bg]}"));\n"
WLOGOUT_BLOCK+="@define-color logout-hover-bg #$(hex "${COLORS[logout_hover_bg]}");\n"
WLOGOUT_BLOCK+="@define-color logout-hover-text #$(hex "${COLORS[logout_hover_text]}");\n"
inject_css_block "$REPO_DIR/.config/wlogout/style.css" "$WLOGOUT_BLOCK"
echo "injected: wlogout/style.css color block"

echo ""
echo "All color files regenerated from $SRC"
