-- HyprFlux — https://github.com/ahmad9059/HyprFlux
-- Monitor config — AUTO-GENERATED by NWG-Displays (will be overwritten).
-- The Lua counterpart of monitors.conf for Hyprland >= 0.55.
--
-- nwg-displays writes this file when you click apply. In hyprland.lua:
--   require("monitors")
--
-- Fallback rule: any monitor not matched below uses preferred mode.
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })

-- Example: detected monitors
-- hl.monitor({ output = "eDP-1", mode = "2560x1440@165", position = "0x0", scale = 1.0 })
-- hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@60", position = "auto", scale = 1 })

-- NOTE: for laptop lid behaviour, see UserConfigs/laptops.lua
-- QEMU/KVM virtual display example:
-- hl.monitor({ output = "Virtual-1", mode = "1920x1080@60", position = "auto", scale = 1 })

-- Mirror example:
-- hl.monitor({ output = "HDMI-A-1", mode = "preferred", position = "auto", scale = 1, mirror = "eDP-1" })

-- 10-bit support (may break screen capture):
-- hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1, bitdepth = 10 })
