# =============================
# Package Configuration
# =============================

# Mandatory packages (always installed)
REQUIRED_PACKAGES=(
  foot
  lsd
  bat
  nvim
  firefox
  tmux
  yazi
  zoxide
  qt6-5compat
  chromium
  npm
  plymouth
  rclone
  github-cli
)

# Required AUR packages (always installed)
YAY_REQUIRED_PACKAGES=()

# Optional Pacman packages (user choice)
PACMAN_PACKAGES=(
  foot
  alacritty
  lsd
  bat
  tmux
  neovim
  tldr
  obs-studio
  vlc
  yazi
  luacheck
  luarocks
  hyprpicker
  obsidian
  github-cli
  noto-fonts-emoji
  ttf-noto-nerd
  noto-fonts
)

# Optional AUR packages (user choice)
YAY_PACKAGES=(
  visual-studio-code-bin
  64gram-desktop-bin
  vesktop
  foliate
  whatsapp-for-linux
  stacer-bin
  localsend-bin
  kiro-bin
)